### ISSUE TITLE
Crear application en Argo para el pull del chart de la web

### ISSUE THREAD

**Issue by dcristobalhMad** [cloudnativerioja/cluster-applications#13]
Se propone crear un recurso application de ArgoCD para que pueda hacer el pull del chart de la web versionado. Depende de https://github.com/cloudnativerioja/official-website/issues/27 y de https://github.com/cloudnativerioja/official-website/issues/28

It is proposed to create an Application resource in order to deploy the versioned official-website chart, depending on these issues

**Comment by sandeepV2** [comment]
Can you please describe the problem in english.
